[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corelib = { path = "../corelib" }
tokio = { version = "*", features = ["full"] }
rumqttd = "0.9.0"
toml = "*"
